"""create fetches and projections tables

Revision ID: 4938bf64fe7e
Revises: 
Create Date: 2026-03-25 15:51:26.608877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4938bf64fe7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('tour', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetch_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('projected_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fetch_id'], ['fetches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projections')
    op.drop_table('fetches')
    # ### end Alembic commands ###
